CC = g++
	
all: blocksmain.cpp Blocksgame.cpp Blocksgame.h
	$(CC) blocksmain.cpp Blocksgame.cpp Blocksgame.h -o sfml-app -L/home/endzi2/SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network -lsfml-audio

